[package]
name = "elvis"
version = "0.2.3"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"
description = "Calling Elvis, is anybody home?"
repository = "https://github.com/clearloop/elvis"
license = "MIT"
documentation = "https://docs.rs/elvis"
homepage = "https://github.com/clearloop/elvis"
include = ["src/**/*", "Cargo.toml", "./README.md"]
keywords = ["js", "wasm", "spa", "web"]
readme = './README.md'

[features]
web = []
default = ["web"]

[dependencies]
elvis-derive = { path = "crates/derive", version = "0.1.0" }
elvis-shared = { path = "crates/shared", version = "0.1.0" }

[workspace]
members = [
  "crates/web",
  "crates/backend",
  "crates/derive",
  "crates/epm",
  "crates/shared",
  "examples/hello-world",
]

[profile.release]
lto = true