[package]
name = "elvis"
version = "0.2.6"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"
description = "Calling Elvis, is anybody home?"
repository = "https://github.com/clearloop/elvis"
license = "MIT"
documentation = "https://docs.rs/elvis"
homepage = "https://github.com/clearloop/elvis"
include = ["src/**/*", "Cargo.toml", "./README.md"]
keywords = ["js", "wasm", "spa", "web"]
readme = './README.md'

[workspace]
members = [
  "crates/web",
  "crates/backend",
  "crates/derive",
  "crates/epm",
  "crates/core",
  
  # Examples
  "examples/hello-world",
  "examples/click",
  "examples/router",
]

[dependencies]
elvis-derive = { path = "crates/derive" }
elvis-core = { path = "crates/core"  }
elvis-web = { path = "crates/web", optional = true }

[features]
web = [ "elvis-web", "elvis-core/web" ]
default = [ "web" ]

[profile.release]
lto = true