[package]
name = "elvis"
version = "0.2.5"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"
description = "Calling Elvis, is anybody home?"
repository = "https://github.com/clearloop/elvis"
license = "MIT"
documentation = "https://docs.rs/elvis"
homepage = "https://github.com/clearloop/elvis"
include = ["src/**/*", "Cargo.toml", "./README.md"]
keywords = ["js", "wasm", "spa", "web"]
readme = './README.md'

[workspace]
members = [
  "crates/web",
  "crates/backend",
  "crates/derive",
  "crates/epm",
  "crates/shared",
  "examples/hello-world",
]

[dependencies]
elvis-derive = { path = "crates/derive", version = "0.1.1" }
elvis-shared = { path = "crates/shared", version = "0.1.1" }
elvis-web = { path = "crates/web", version = "0.1.5", optional = true }

[features]
web = [ "elvis-web", "elvis-shared/web" ]
default = [ "web" ]

[profile.release]
lto = true