//! Elvis derive macros
#![warn(missing_docs)]
extern crate proc_macro;

use self::proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, Data, DataStruct, DeriveInput, Fields};

/// Basic elvis attr macro
#[proc_macro_derive(Setter)]
pub fn setter(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let fields = match &input.data {
        Data::Struct(DataStruct {
            fields: Fields::Named(fields),
            ..
        }) => &fields.named,
        _ => panic!("expected a struct with named fields"),
    };
    let field_name = fields.iter().map(|field| &field.ident);
    let field_type = fields.iter().map(|field| &field.ty);
    let struct_name = &input.ident;

    // TODO: Generate docs

    TokenStream::from(quote! {
        impl #struct_name {
            #(
                /// Auto generated by elvis-core-support
                pub fn #field_name(mut self, v: #field_type) -> Self {
                    self.#field_name = v;
                    self
                }
            )*
        }
    })
}
