use elvis::{Colors as ElvisColors, Serde};
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub enum Colors {
    Amber,
    AmberAccent,
    Black,
    Blue,
    BlueAccent,
    BlueGrey,
    Brown,
    Cyan,
    CyanAccent,
    DeepOrange,
    DeepOrangeAccent,
    DeepPurple,
    DeepPurpleAccent,
    Green,
    GreenAccent,
    Grey,
    Indigo,
    IndigoAccent,
    LightBlue,
    LightBlueAccent,
    LightGreen,
    LightGreenAccent,
    Lime,
    LimeAccent,
    Orange,
    OrangeAccent,
    Pink,
    PinkAccent,
    Purple,
    PurpleAccent,
    Red,
    RedAccent,
    Teal,
    TealAccent,
    Transparent,
    White,
    Yellow,
    YellowAccent,
}

impl Colors {
    pub fn ser(&self) -> String {
        match self {
            Self::Amber => ElvisColors::Amber.ser(),
            Self::AmberAccent => ElvisColors::AmberAccent.ser(),
            Self::Black => ElvisColors::Black.ser(),
            Self::Blue => ElvisColors::Blue.ser(),
            Self::BlueAccent => ElvisColors::BlueAccent.ser(),
            Self::BlueGrey => ElvisColors::BlueGrey.ser(),
            Self::Brown => ElvisColors::Brown.ser(),
            Self::Cyan => ElvisColors::Cyan.ser(),
            Self::CyanAccent => ElvisColors::CyanAccent.ser(),
            Self::DeepOrange => ElvisColors::DeepOrange.ser(),
            Self::DeepOrangeAccent => ElvisColors::DeepOrangeAccent.ser(),
            Self::DeepPurple => ElvisColors::DeepPurple.ser(),
            Self::DeepPurpleAccent => ElvisColors::DeepPurpleAccent.ser(),
            Self::Green => ElvisColors::Green.ser(),
            Self::GreenAccent => ElvisColors::GreenAccent.ser(),
            Self::Grey => ElvisColors::Grey.ser(),
            Self::Indigo => ElvisColors::Indigo.ser(),
            Self::IndigoAccent => ElvisColors::IndigoAccent.ser(),
            Self::LightBlue => ElvisColors::LightBlue.ser(),
            Self::LightBlueAccent => ElvisColors::LightBlueAccent.ser(),
            Self::LightGreen => ElvisColors::LightGreen.ser(),
            Self::LightGreenAccent => ElvisColors::LightGreenAccent.ser(),
            Self::Lime => ElvisColors::Lime.ser(),
            Self::LimeAccent => ElvisColors::LimeAccent.ser(),
            Self::Orange => ElvisColors::Orange.ser(),
            Self::OrangeAccent => ElvisColors::OrangeAccent.ser(),
            Self::Pink => ElvisColors::Pink.ser(),
            Self::PinkAccent => ElvisColors::PinkAccent.ser(),
            Self::Purple => ElvisColors::Purple.ser(),
            Self::PurpleAccent => ElvisColors::PurpleAccent.ser(),
            Self::Red => ElvisColors::Red.ser(),
            Self::RedAccent => ElvisColors::RedAccent.ser(),
            Self::Teal => ElvisColors::Teal.ser(),
            Self::TealAccent => ElvisColors::TealAccent.ser(),
            Self::Transparent => ElvisColors::Transparent.ser(),
            Self::White => ElvisColors::White.ser(),
            Self::Yellow => ElvisColors::Yellow.ser(),
            Self::YellowAccent => ElvisColors::YellowAccent.ser(),
        }
    }
}
