name: elvis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master
      - name: Build
        run: cargo build -all --verbose
      - name: Run tests
        run: cargo test -all --verbose
